version: '3'
services:
  navidrome:
    image: deluan/navidrome:0.52.5
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - ./navidrome-music:/music
      - ./navidrome-data:/data 
    restart: unless-stopped
